apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: kafka-producer
  name: kafka-producer
spec:
  parallelism: 5
  completions: 5
  backoffLimit: 1
  template:
    metadata:
      name: kafka-producer
      labels:
        app: kafka-producer
    spec:
      restartPolicy: Never
      containers:
      - name: kafka-producer
        image: strimzi/kafka:build-kafka-4.0.0
        command: [ "bin/kafka-producer-perf-test.sh" ]
        args: [ "--topic", "load-test", "--throughput", "1000000000", "--num-records", "1000000000", "--producer-props", "acks=all", "bootstrap.servers=inkless-cluster-kafka-bootstrap:9092", "--record-size", "1000" ]
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: kafka-consumer
  name: kafka-consumer
spec:
  parallelism: 5
  completions: 5
  backoffLimit: 1
  template:
    metadata:
      name: kafka-consumer
      labels:
        app: kafka-consumer
    spec:
      restartPolicy: Never
      containers:
      - name: kafka-consumer
        image: strimzi/kafka:build-kafka-4.0.0
        command: [ "/bin/sh" ]
        args: [ "-c", "echo \"group.id=load-group-1\" >> /tmp/consumer.config; bin/kafka-consumer-perf-test.sh --topic load-test --messages 1000000000 --bootstrap-server inkless-cluster-kafka-bootstrap:9092 --show-detailed-stats --timeout 300000 --group load-consumer --consumer.config /tmp/consumer.config" ]
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: kafka-consumer2
  name: kafka-consumer2
spec:
  parallelism: 5
  completions: 5
  backoffLimit: 1
  template:
    metadata:
      name: kafka-consumer2
      labels:
        app: kafka-consumer2
    spec:
      restartPolicy: Never
      containers:
      - name: kafka-consumer
        image: strimzi/kafka:build-kafka-4.0.0
        command: [ "/bin/sh" ]
        args: [ "-c", "echo \"group.id=load-group-2\" > /tmp/consumer.config; bin/kafka-consumer-perf-test.sh --topic load-test --messages 1000000000 --bootstrap-server inkless-cluster-kafka-bootstrap:9092 --show-detailed-stats --timeout 300000 --group load-consumer2 --consumer.config /tmp/consumer.config" ]
