apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: load-test
  labels:
    strimzi.io/cluster: inkless-cluster
spec:
  partitions: 100
  replicas: 1
  config:
    min.insync.replicas: 1
    retention.bytes: 10737418240 # ~10 Gi
    retention.ms: 7200000 # 1 hour
    segment.bytes: 10485760 # ~10MB
    file.delete.delay.ms: 1000
    diskless.enable: true
    local.retention.ms: 60000 # 1 minute
    local.retention.bytes: 50000000 # 50 MB